n = input('digite algo: ')
print(type(n))
print('Só tem espaços? ', n.isspace())
print('é um número? ', n.isnumeric())
print('é um valor alfanúmerico? ', n.isalnum())
print('é um valor alfabético? ', n.isalpha())
print('é um valor alpha em letras maiusculas? ', n.isupper())
print('é um valor alpha em letras minusculas? ', n.islower())
print('Tem maiusculas no inicio de cada palavra? ', n.istitle())
